### ISSUE TITLE
Is it possible to use sso pingfederate in an angular cli or a express cli app, so that I can achieve single sign on

### ISSUE THREAD

**Issue by rishiwhite11** [pivotal-cf/identity-sample-apps#13]

**Comment by tnwang** [comment]
Ping Federate is supported.

CLIs inherently use password grant type which does not support Single Sign-On via sessions since it is not a browser flow - users can use the same password they use for their enterprise setting.

You can read more about PingFederate integration and the password grant type at our SSO documents here http://docs.pivotal.io/p-identity.
